version: 2
jobs:
  build:
    working_directory: ~/jackup
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            pytest
