version: 2
jobs:
  build:
    working_directory: ~/jackup
    docker:
      - image: circleci/python:3.8
    resource_class: small
    steps:
      - checkout
      - run:
          command: |
            pip install --upgrade pip
            pip install --upgrade -r requirements-dev.txt -r requirements.txt
            pip install .
            pytest
